import uuid
DEFAULt_DOC_TYPE_ID = uuid.UUID("00000000-0000-0000-0000-000000000000")
DEFAULt_DOC_TYPE_NAME = "default"
actions = [
    {'type': 'team',
     'name': '获取团队用户列表', 'action': 'POST /team/usr'},
    {'type': 'team',
     'name': '获取团队消息列表', 'action': 'POST /team/msg'},
    {'type': 'team',
     'name': '发送团队邀请', 'action': 'POST /team/invitation'},
    {'type': 'team',
     'name': '处理用户申请', 'action': 'PUT /usr_msg'},
    {'type': 'team',
     'name': '更新团队信息', 'action': 'PUT /team'},
    {'type': 'team',
     'name': '更新团队用户角色', 'action': 'PUT /team/usr'},
    {'type': 'team',
     'name': '移交团队', 'action': 'PUT /team/author'},
    {'type': 'team',
     'name': '解散团队', 'action': 'DELETE /team'},
    {'type': 'team',
     'name': '剔除团队用户', 'action': 'DELETE /team/usr'},
    {'type': 'knowledge_base',
     'name': '获取团队下知识库列表', 'action': 'POST /kb/team'},
    {'type': 'knowledge_base',
     'name': '获取知识库文档类型', 'action': 'GET /kb/doc_type'},
    {'type': 'knowledge_base',
     'name': '下载知识库文件', 'action': 'GET /kb/download'},
    {'type': 'knowledge_base',
     'name': '创建知识库', 'action': 'POST /kb'},
    {'type': 'knowledge_base',
     'name': '导入知识库', 'action': 'POST /kb/import'},
    {'type': 'knowledge_base',
     'name': '导出知识库', 'action': 'POST /kb/export'},
    {'type': 'knowledge_base',
     'name': '更新知识库信息', 'action': 'PUT /kb'},
    {'type': 'knowledge_base',
     'name': '删除知识库', 'action': 'DELETE /kb'},
    {'type': 'chunk',
     'name': '获取文档解析结果列表', 'action': 'POST /chunk/list'},
    {'type': 'chunk',
     'name': '检索文档解析结果', 'action': 'POST /chunk/search'},
    {'type': 'chunk',
     'name': '更新文档解析结果', 'action': 'PUT /chunk'},
    {'type': 'document',
     'name': '获取文档列表', 'action': 'POST /doc/list'},
    {'type': 'document',
     'name': '下载文档', 'action': 'GET /doc/download'},
    {'type': 'document',
     'name': '获取文档报告', 'action': 'GET /doc/report'},
    {'type': 'document',
     'name': '下载文档报告', 'action': 'GET /doc/report/download'},
    {'type': 'document',
     'name': '创建文档', 'action': 'POST /doc'},
    {'type': 'document',
     'name': '解析文档', 'action': 'POST /doc/parse'},
    {'type': 'document',
     'name': '更新文档信息', 'action': 'PUT /doc'},
    {'type': 'document',
     'name': '删除文档', 'action': 'DELETE /doc'},
    {'type': 'dataset_data',
     'name': '获取数据集列表', 'action': 'POST /dataset/list'},
    {'type': 'dataset_data',
     'name': '获取测试数据列表', 'action': 'POST /dataset/data'},
    {'type': 'dataset_data',
             'name': '获取测试数据下是否有测试任务', 'action': 'GET /dataset/testing/exist'},
    {'type': 'dataset_data',
     'name': '下载数据集', 'action': 'GET /dataset/download'},
    {'type': 'dataset_data',
     'name': '新建数据集', 'action': 'POST /dataset'},
    {'type': 'dataset_data',
     'name': '导入数据集', 'action': 'POST /dataset/import'},
    {'type': 'dataset_data',
     'name': '导出数据集', 'action': 'POST /dataset/export'},
    {'type': 'dataset_data',
     'name': '生成数据集', 'action': 'POST /dataset/generate'},
    {'type': 'dataset_data',
     'name': '修改数据集信息', 'action': 'PUT /dataset'},
    {'type': 'dataset_data',
     'name': '修改测试样例', 'action': 'PUT /dataset/data'},
    {'type': 'dataset_data',
     'name': '删除数据集', 'action': 'DELETE /dataset'},
    {'type': 'dataset_data',
     'name': '删除测试样例', 'action': 'DELETE /dataset/data'},
    {'type': 'testing',
     'name': '获取测试列表', 'action': 'POST /testing/list'},
    {'type': 'testing',
     'name': '获取测试用例列表', 'action': 'POST /testing/testcase'},
    {'type': 'testing',
     'name': '下载测试结果', 'action': 'GET /testing/download'},
    {'type': 'testing',
     'name': '创建测试', 'action': 'POST /testing'},
    {'type': 'testing',
     'name': '运行测试', 'action': 'POST /testing/run'},
    {'type': 'testing',
     'name': '更新测试信息', 'action': 'PUT /testing'},
    {'type': 'testing',
     'name': '删除测试', 'action': 'DELETE /testing'},
    {'type': 'role',
     'name': '获取角色操作列表', 'action': 'GET /role/action'},
    {'type': 'role',
     'name': '获取角色列表', 'action': 'POST /role/list'},
    {'type': 'role',
     'name': '创建角色', 'action': 'POST /role'},
    {'type': 'role',
     'name': '更新角色信息', 'action': 'PUT /role'},
    {'type': 'role',
     'name': '删除角色', 'action': 'DELETE /role'},
    {'type': 'task',
     'name': '获取任务列表', 'action': 'POST /task'},
    {'type': 'task',
     'name': '获取任务报告', 'action': 'GET /task/report'},
    {'type': 'task',
     'name': '删除单个任务', 'action': 'DELETE /task/one'},
    {'type': 'task',
     'name': '删除单个任务', 'action': 'DELETE /task/all'}]
default_roles = [
    {
        "id": uuid.UUID("00000000-0000-0000-0000-000000000001"),
        "name": "创建者",
        "is_unique": True,
        "actions": [
            {'type': 'team',
             'name': '获取团队用户列表', 'action': 'POST /team/usr'},
            {'type': 'team',
             'name': '获取团队消息列表', 'action': 'POST /team/msg'},
            {'type': 'team',
             'name': '发送团队邀请', 'action': 'POST /team/invitation'},
            {'type': 'team',
             'name': '处理用户申请', 'action': 'PUT /usr_msg'},
            {'type': 'team',
             'name': '更新团队信息', 'action': 'PUT /team'},
            {'type': 'team',
             'name': '更新团队用户角色', 'action': 'PUT /team/usr'},
            {'type': 'team',
             'name': '移交团队', 'action': 'PUT /team/author'},
            {'type': 'team',
             'name': '解散团队', 'action': 'DELETE /team'},
            {'type': 'team',
             'name': '剔除团队用户', 'action': 'DELETE /team/usr'},
            {'type': 'knowledge_base',
             'name': '获取团队下知识库列表', 'action': 'POST /kb/team'},
            {'type': 'knowledge_base',
             'name': '获取知识库文档类型', 'action': 'GET /kb/doc_type'},
            {'type': 'knowledge_base',
             'name': '下载知识库文件', 'action': 'GET /kb/download'},
            {'type': 'knowledge_base',
             'name': '创建知识库', 'action': 'POST /kb'},
            {'type': 'knowledge_base',
             'name': '导入知识库', 'action': 'POST /kb/import'},
            {'type': 'knowledge_base',
             'name': '导出知识库', 'action': 'POST /kb/export'},
            {'type': 'knowledge_base',
             'name': '更新知识库信息', 'action': 'PUT /kb'},
            {'type': 'knowledge_base',
             'name': '删除知识库', 'action': 'DELETE /kb'},
            {'type': 'chunk',
             'name': '获取文档解析结果列表', 'action': 'POST /chunk/list'},
            {'type': 'chunk',
             'name': '检索文档解析结果', 'action': 'POST /chunk/search'},
            {'type': 'chunk',
             'name': '更新文档解析结果', 'action': 'PUT /chunk'},
            {'type': 'document',
             'name': '获取文档列表', 'action': 'POST /doc/list'},
            {'type': 'document',
             'name': '下载文档', 'action': 'GET /doc/download'},
            {'type': 'document',
             'name': '获取文档报告', 'action': 'GET /doc/report'},
            {'type': 'document',
             'name': '下载文档报告', 'action': 'GET /doc/report/download'},
            {'type': 'document',
             'name': '创建文档', 'action': 'POST /doc'},
            {'type': 'document',
             'name': '解析文档', 'action': 'POST /doc/parse'},
            {'type': 'document',
             'name': '更新文档信息', 'action': 'PUT /doc'},
            {'type': 'document',
             'name': '删除文档', 'action': 'DELETE /doc'},
            {'type': 'dataset_data',
             'name': '获取数据集列表', 'action': 'POST /dataset/list'},
            {'type': 'dataset_data',
             'name': '获取测试数据列表', 'action': 'POST /dataset/data'},
            {'type': 'dataset_data',
             'name': '获取测试数据下是否有测试任务', 'action': 'GET /dataset/testing/exist'},
            {'type': 'dataset_data',
             'name': '下载数据集', 'action': 'GET /dataset/download'},
            {'type': 'dataset_data',
             'name': '新建数据集', 'action': 'POST /dataset'},
            {'type': 'dataset_data',
             'name': '导入数据集', 'action': 'POST /dataset/import'},
            {'type': 'dataset_data',
             'name': '导出数据集', 'action': 'POST /dataset/export'},
            {'type': 'dataset_data',
             'name': '生成数据集', 'action': 'POST /dataset/generate'},
            {'type': 'dataset_data',
             'name': '修改数据集信息', 'action': 'PUT /dataset'},
            {'type': 'dataset_data',
             'name': '修改测试样例', 'action': 'PUT /dataset/data'},
            {'type': 'dataset_data',
             'name': '删除数据集', 'action': 'DELETE /dataset'},
            {'type': 'dataset_data',
             'name': '删除测试样例', 'action': 'DELETE /dataset/data'},
            {'type': 'testing',
             'name': '获取测试列表', 'action': 'POST /testing/list'},
            {'type': 'testing',
             'name': '获取测试用例列表', 'action': 'POST /testing/testcase'},
            {'type': 'testing',
             'name': '下载测试结果', 'action': 'GET /testing/download'},
            {'type': 'testing',
             'name': '创建测试', 'action': 'POST /testing'},
            {'type': 'testing',
             'name': '运行测试', 'action': 'POST /testing/run'},
            {'type': 'testing',
             'name': '更新测试信息', 'action': 'PUT /testing'},
            {'type': 'testing',
             'name': '删除测试', 'action': 'DELETE /testing'},
            {'type': 'role',
             'name': '获取角色操作列表', 'action': 'GET /role/action'},
            {'type': 'role',
             'name': '获取角色列表', 'action': 'POST /role/list'},
            {'type': 'role',
             'name': '创建角色', 'action': 'POST /role'},
            {'type': 'role',
             'name': '更新角色信息', 'action': 'PUT /role'},
            {'type': 'role',
             'name': '删除角色', 'action': 'DELETE /role'},
            {'type': 'task',
             'name': '获取任务列表', 'action': 'POST /task'},
            {'type': 'task',
             'name': '获取任务报告', 'action': 'GET /task/report'},
            {'type': 'task',
             'name': '删除单个任务', 'action': 'DELETE /task/one'},
            {'type': 'task',
             'name': '删除单个任务', 'action': 'DELETE /task/all'}],
        "editable": False,
    }, {
        "id": uuid.UUID("00000000-0000-0000-0000-000000000002"),
        "name": "管理员",
        "is_unique": False,
        "actions": [
            {'type': 'team',
             'name': '获取团队用户列表', 'action': 'POST /team/usr'},
            {'type': 'team',
             'name': '获取团队消息列表', 'action': 'POST /team/msg'},
            {'type': 'team',
             'name': '发送团队邀请', 'action': 'POST /team/invitation'},
            {'type': 'team',
             'name': '处理用户申请', 'action': 'PUT /usr_msg'},
            {'type': 'team',
             'name': '更新团队用户角色', 'action': 'PUT /team/usr'},
            {'type': 'team',
             'name': '剔除团队用户', 'action': 'DELETE /team/usr'},
            {'type': 'knowledge_base',
             'name': '获取团队下知识库列表', 'action': 'POST /kb/team'},
            {'type': 'knowledge_base',
             'name': '获取知识库文档类型', 'action': 'GET /kb/doc_type'},
            {'type': 'knowledge_base',
             'name': '下载知识库文件', 'action': 'GET /kb/download'},
            {'type': 'knowledge_base',
             'name': '创建知识库', 'action': 'POST /kb'},
            {'type': 'knowledge_base',
             'name': '导入知识库', 'action': 'POST /kb/import'},
            {'type': 'knowledge_base',
             'name': '导出知识库', 'action': 'POST /kb/export'},
            {'type': 'knowledge_base',
             'name': '更新知识库信息', 'action': 'PUT /kb'},
            {'type': 'knowledge_base',
             'name': '删除知识库', 'action': 'DELETE /kb'},
            {'type': 'chunk',
             'name': '获取文档解析结果列表', 'action': 'POST /chunk/list'},
            {'type': 'chunk',
             'name': '检索文档解析结果', 'action': 'POST /chunk/search'},
            {'type': 'chunk',
             'name': '更新文档解析结果', 'action': 'PUT /chunk'},
            {'type': 'document',
             'name': '获取文档列表', 'action': 'POST /doc/list'},
            {'type': 'document',
             'name': '下载文档', 'action': 'GET /doc/download'},
            {'type': 'document',
             'name': '获取文档报告', 'action': 'GET /doc/report'},
            {'type': 'document',
             'name': '下载文档报告', 'action': 'GET /doc/report/download'},
            {'type': 'document',
             'name': '创建文档', 'action': 'POST /doc'},
            {'type': 'document',
             'name': '解析文档', 'action': 'POST /doc/parse'},
            {'type': 'document',
             'name': '更新文档信息', 'action': 'PUT /doc'},
            {'type': 'document',
             'name': '删除文档', 'action': 'DELETE /doc'},
            {'type': 'dataset_data',
             'name': '获取数据集列表', 'action': 'POST /dataset/list'},
            {'type': 'dataset_data',
             'name': '获取测试数据列表', 'action': 'POST /dataset/data'},
            {'type': 'dataset_data',
             'name': '获取测试数据下是否有测试任务', 'action': 'GET /dataset/testing/exist'},
            {'type': 'dataset_data',
             'name': '下载数据集', 'action': 'GET /dataset/download'},
            {'type': 'dataset_data',
             'name': '新建数据集', 'action': 'POST /dataset'},
            {'type': 'dataset_data',
             'name': '导入数据集', 'action': 'POST /dataset/import'},
            {'type': 'dataset_data',
             'name': '导出数据集', 'action': 'POST /dataset/export'},
            {'type': 'dataset_data',
             'name': '生成数据集', 'action': 'POST /dataset/generate'},
            {'type': 'dataset_data',
             'name': '修改数据集信息', 'action': 'PUT /dataset'},
            {'type': 'dataset_data',
             'name': '修改测试样例', 'action': 'PUT /dataset/data'},
            {'type': 'dataset_data',
             'name': '删除数据集', 'action': 'DELETE /dataset'},
            {'type': 'dataset_data',
             'name': '删除测试样例', 'action': 'DELETE /dataset/data'},
            {'type': 'testing',
             'name': '获取测试列表', 'action': 'POST /testing/list'},
            {'type': 'testing',
             'name': '获取测试用例列表', 'action': 'POST /testing/testcase'},
            {'type': 'testing',
             'name': '下载测试结果', 'action': 'GET /testing/download'},
            {'type': 'testing',
             'name': '创建测试', 'action': 'POST /testing'},
            {'type': 'testing',
             'name': '运行测试', 'action': 'POST /testing/run'},
            {'type': 'testing',
             'name': '更新测试信息', 'action': 'PUT /testing'},
            {'type': 'testing',
             'name': '删除测试', 'action': 'DELETE /testing'},
            {'type': 'role',
             'name': '获取角色操作列表', 'action': 'GET /role/action'},
            {'type': 'role',
             'name': '获取角色列表', 'action': 'POST /role/list'},
            {'type': 'task',
             'name': '获取任务列表', 'action': 'POST /task'},
            {'type': 'task',
             'name': '获取任务报告', 'action': 'GET /task/report'},
            {'type': 'task',
             'name': '删除单个任务', 'action': 'DELETE /task/one'},
            {'type': 'task',
             'name': '删除单个任务', 'action': 'DELETE /task/all'}],
        "editable": False,
    }, {
        "id": uuid.UUID("00000000-0000-0000-0000-000000000003"),
        "name": "成员",
        "is_unique": False,
        "actions":
            [
                {'type': 'team',
                 'name': '获取团队用户列表', 'action': 'POST /team/usr'},
                {'type': 'team',
                    'name': '获取团队消息列表', 'action': 'POST /team/msg'},
                {'type': 'knowledge_base',
                    'name': '获取团队下知识库列表', 'action': 'POST /kb/team'},
                {'type': 'knowledge_base',
                    'name': '获取知识库文档类型', 'action': 'GET /kb/doc_type'},
                {'type': 'chunk',
                    'name': '获取文档解析结果列表', 'action': 'POST /chunk/list'},
                {'type': 'document',
                    'name': '获取文档列表', 'action': 'POST /doc/list'},
                {'type': 'document',
                    'name': '下载文档', 'action': 'GET /doc/download'},
                {'type': 'dataset_data',
                    'name': '获取数据集列表', 'action': 'POST /dataset/list'},
                {'type': 'dataset_data',
                    'name': '获取测试数据列表', 'action': 'POST /dataset/data'},
                {'type': 'testing',
                    'name': '获取测试列表', 'action': 'POST /testing/list'},
                {'type': 'testing',
                    'name': '获取测试用例列表', 'action': 'POST /testing/testcase'},
                {'type': 'role',
                    'name': '获取角色操作列表', 'action': 'GET /role/action'},
                {'type': 'role',
                    'name': '获取角色列表', 'action': 'POST /role/list'}
        ],
        "editable": False,
    }
]

DOC_PATH_IN_MINIO = "witchaind-doc"
REPORT_PATH_IN_MINIO = "witchaind-report"
IMAGE_PATH_IN_MINIO = "witchaind-image"
EXPORT_KB_PATH_IN_MINIO = "witchaind-kb-export"
IMPORT_KB_PATH_IN_MINIO = "witchaind-kb-import"
EXPORT_DATASET_PATH_IN_MINIO = "witchaind-dataset-export"
IMPORT_DATASET_PATH_IN_MINIO = "witchaind-dataset-import"
TESTING_REPORT_PATH_IN_MINIO = "witchaind-testing-report"

DOC_PATH_IN_OS = "./witchaind-doc"
EXPORT_KB_PATH_IN_OS = "./witchaind-kb-export"
IMPORT_KB_PATH_IN_OS = "./witchaind-kb-import"
EXPORT_DATASET_PATH_IN_OS = "./witchaind-dataset-export"
IMPORT_DATASET_PATH_IN_OS = "./witchaind-dataset-import"
TESTING_REPORT_PATH_IN_OS = "./witchaind-testing-report"
